title: BIG CODING BLOG, ITS UPPERCASED BECAUSE ITS AMAZING.  
author: ME (ERIC, the cool epic and amazing dude!!)  
email: ericjlindburg@students.k12.com
description: > big amazing coding blofg!!

# social links
twitter_username: no. lol. # DO NOT include the @ character, or else the build will fail!
github_username:  no. lol. # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
